#############################################################################
# Makefile for building: Bin/BoostSerializationMinimalExample
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  BoostSerializationMinimalExample.pro
# Template: app
# Command: /Users/wolfgangmeyerle/Qt/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile BoostSerializationMinimalExample.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Cellar/boost/1.63.0/include -I../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I../../../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/wolfgangmeyerle/Qt/5.7/clang_64/lib
QMAKE         = /Users/wolfgangmeyerle/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = BoostSerializationMinimalExample1.0.0
DISTDIR = /Users/wolfgangmeyerle/Documents/workspace/BoostSerializationMinimalExample/Build/BoostSerializationMinimalExample1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/wolfgangmeyerle/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/wolfgangmeyerle/Qt/5.7/clang_64/lib -L/usr/local/Cellar/boost/1.63.0/lib -lboost_system -lboost_filesystem -lboost_serialization -lboost_program_options -lboost_thread-mt -framework QtCore -framework DiskArbitration -framework IOKit 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = Build/

####### Files

SOURCES       = main.cpp 
OBJECTS       = Build/main.o
DIST          = ../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		BoostSerializationMinimalExample.pro  main.cpp
QMAKE_TARGET  = BoostSerializationMinimalExample
DESTDIR       = Bin/
TARGET        = Bin/BoostSerializationMinimalExample


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d Bin/ || mkdir -p Bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BoostSerializationMinimalExample.pro ../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		BoostSerializationMinimalExample.pro \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile BoostSerializationMinimalExample.pro
../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.7/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.7/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.7/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.7/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.7/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.7/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.7/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.7/clang_64/mkspecs/features/lex.prf:
BoostSerializationMinimalExample.pro:
../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile BoostSerializationMinimalExample.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

Build/main.o: main.cpp /usr/local/Cellar/boost/1.63.0/include/boost/serialization/export.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/user.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/select_compiler_config.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/nvcc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/gcc_xml.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/cray.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/common_edg.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/comeau.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/pathscale.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/intel.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/visualc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/gcc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/clang.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/digitalmars.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/kai.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/sgi_mipspro.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/compaq_cxx.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/greenhills.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/codegear.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/borland.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/metrowerks.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/sunpro_cc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/hp_acc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/mpw.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/vacpp.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/compiler/pgi.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/select_stdlib_config.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/stdlib/stlport.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/stdlib/libcomo.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/no_tr1/utility.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/stdlib/roguewave.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/stdlib/libcpp.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/stdlib/libstdcpp3.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/stdlib/sgi.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/stdlib/msl.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/posix_features.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/stdlib/vacpp.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/stdlib/modena.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/stdlib/dinkumware.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/select_platform_config.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/linux.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/bsd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/solaris.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/irix.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/hpux.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/cygwin.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/win32.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/beos.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/macos.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/aix.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/amigaos.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/qnxnto.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/vxworks.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/symbian.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/cray.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/platform/vms.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/suffix.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/static_assert.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/detail/workaround.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/stringize.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/config/config.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_polymorphic.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/intrinsics.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/detail/config.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/version.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_same.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/integral_constant.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_reference.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_lvalue_reference.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_rvalue_reference.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_volatile.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_void.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_class.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_union.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/detail/yes_no_type.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_scalar.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_arithmetic.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_integral.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_floating_point.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_enum.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/add_reference.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_convertible.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_array.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_abstract.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/add_lvalue_reference.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/add_rvalue_reference.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_function.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/detail/is_function_ptr_helper.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/detail/is_function_ptr_tester.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/remove_reference.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/declval.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_pointer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_member_pointer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_member_function_pointer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/detail/is_mem_fun_pointer_impl.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/remove_cv.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/detail/is_mem_fun_pointer_tester.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/assert.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/not.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/bool.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/bool_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/adl_barrier.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/adl.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/msvc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/intel.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/gcc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/workaround.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/integral_c_tag.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/static_constant.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/nttp_decl.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/nttp.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/cat.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/nested_type_wknd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/na_spec.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/lambda_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/void_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/na.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/na_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/ctps.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/lambda.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/ttp.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/int.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/int_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/integral_wrapper.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/static_cast.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/lambda_arity_param.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/template_arity_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/arity.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/dtp.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/preprocessor/params.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/preprocessor.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/comma_if.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/punctuation/comma_if.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/control/if.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/control/iif.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/logical/bool.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/facilities/empty.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/punctuation/comma.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/repeat.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/repetition/repeat.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/debug/error.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/detail/auto_rec.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/detail/dmc/auto_rec.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/tuple/eat.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/inc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/arithmetic/inc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/preprocessor/enum.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/preprocessor/def_params_tail.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/limits/arity.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/logical/and.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/logical/bitand.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/identity.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/facilities/identity.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/empty.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/preprocessor/filter_params.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/preprocessor/sub.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/preprocessor/tuple.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/arithmetic/sub.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/arithmetic/dec.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/control/while.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/list/fold_left.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/list/detail/edg/fold_left.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/control/expr_iif.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/list/adt.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/detail/is_binary.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/detail/check.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/logical/compl.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/list/detail/dmc/fold_left.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/tuple/elem.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/facilities/expand.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/facilities/overload.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/variadic/size.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/tuple/rem.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/tuple/detail/is_single_return.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/facilities/is_1.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/facilities/is_empty.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/facilities/is_empty_variadic.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/punctuation/is_begin_parens.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/punctuation/detail/is_begin_parens.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/facilities/detail/is_empty.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/detail/split.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/tuple/size.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/variadic/elem.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/list/detail/fold_left.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/list/fold_right.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/list/detail/edg/fold_right.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/list/detail/fold_right.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/list/reverse.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/control/detail/edg/while.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/control/detail/msvc/while.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/control/detail/dmc/while.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/control/detail/while.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/arithmetic/add.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/eti.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/overload_resolution.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/lambda_support.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/yes_no.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/arrays.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/tuple/to_list.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/list/for_each_i.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/repetition/for.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/repetition/detail/edg/for.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/repetition/detail/msvc/for.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/repetition/detail/dmc/for.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/repetition/detail/for.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/value_wknd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/integral.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/gpu.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/pp_counter.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/if.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/and.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/use_preprocessed.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/include_preprocessed.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/compiler.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/logical_op.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/preprocessor/ext_params.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/dec.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/extended_type_info.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/assert.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/current_function.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/noncopyable.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/core/noncopyable.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/config.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/auto_link.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/abi_prefix.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/abi_suffix.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/static_warning.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/print.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/identity.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/eval_if.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/assume_abstract.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/force_include.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/singleton.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/auto_link_archive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/decl.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/abi_prefix.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/abi_suffix.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/register_archive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/tracking.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/equal_to.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/comparison_op.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/numeric_op.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/numeric_cast.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/apply_wrap.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/has_apply.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/has_xxx.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/type_wrapper.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/has_xxx.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/msvc_typename.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/array/elem.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/array/data.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/array/size.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/repetition/enum_params.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/repetition/enum_trailing_params.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/has_apply.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/msvc_never_true.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/preprocessor/add.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/bcc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/iterate.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/iteration/iterate.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/slot/slot.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/slot/detail/def.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/msvc_dtw.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/tag.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/void.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/has_tag.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/numeric_cast_utils.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/forwarding.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/msvc_eti_base.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/is_msvc_eti_arg.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/preprocessor/partial_spec_params.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/preprocessor/repeat.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/greater.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_base_and_derived.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/level.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_fundamental.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/integral_c.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/integral_c_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/level_enum.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/tracking_enum.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/type_info_implementation.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/traits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/base_object.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_const.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/access.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/void_cast_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/binary_oarchive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/binary_oarchive_impl.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/basic_binary_oprimitive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/cstdint.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/limits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/integer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/integer_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/integer_traits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/scoped_ptr.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/scoped_ptr.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/checked_delete.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/core/checked_delete.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_nullptr_t.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_disable_deprecated.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/operator_bool.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/throw_exception.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/is_bitwise_serializable.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/array.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/nvp.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/split_member.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/wrapper.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/collection_size_type.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/strong_typedef.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/operators.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/operators_v1.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/split_free.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/serialization.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/always.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/preprocessor/default_params.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/arity_spec.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/apply.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/apply_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/placeholders.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/arg.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/arg_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/na_assert.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/arg_typedef.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/lambda.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/bind.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/bind_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/bind.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/config/dmc_ambiguous_ctps.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/next.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/next_prior.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/common_name_wknd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/protect.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/count_args.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/expr_if.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/control/expr_if.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/enum_shifted_params.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/repetition/enum_shifted_params.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/full_lambda.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/quote.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/has_type.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/template_arity.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/has_rebind.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/msvc_is_class.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/preprocessor/range.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/seq/subseq.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/seq/first_n.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/seq/detail/split.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/seq/rest_n.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/comparison/not_equal.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/seq/detail/is_empty.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/seq/size.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/seq/fold_left.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/seq/seq.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/seq/elem.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/aux_/lambda_no_ctps.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/is_placeholder.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/remove_const.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/array.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/swap.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/core/swap.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/detail/iterator.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/throw_exception.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/exception/exception.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/functional/hash_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/functional/hash/hash_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/basic_streambuf_locale_saver.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/codecvt_null.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/archive_exception.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/basic_binary_oarchive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/common_oarchive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/basic_oarchive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/basic_archive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/helper_collection.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/shared_ptr.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/config/no_tr1/memory.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/shared_count.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/bad_weak_ptr.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_has_sync.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_nt.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/detail/sp_typeinfo.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/core/typeinfo.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/core/demangle.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_std_atomic.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_spin.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/spinlock_pool.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/spinlock.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/spinlock_std_atomic.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/yield_k.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/language.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/language/stdc.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/version_number.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/make.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/detail/test.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/language/stdcpp.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/language/objc.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/alpha.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/arm.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/blackfin.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/convex.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/ia64.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/m68k.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/mips.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/parisc.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/ppc.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/pyramid.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/rs6k.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/sparc.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/superh.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/sys370.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/sys390.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/x86.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/x86/32.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/x86/64.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/architecture/z.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/borland.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/detail/comp_detected.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/clang.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/comeau.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/compaq.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/diab.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/digitalmars.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/dignus.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/edg.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/ekopath.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/gcc_xml.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/gcc.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/greenhills.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/hp_acc.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/iar.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/ibm.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/intel.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/kai.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/llvm.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/metaware.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/metrowerks.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/microtec.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/mpw.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/palm.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/pgi.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/sgi_mipspro.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/sunpro.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/tendra.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/visualc.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/compiler/watcom.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/c.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/c/_prefix.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/detail/_cassert.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/c/gnu.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/c/uc.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/c/vms.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/c/zos.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/std.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/std/_prefix.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/detail/_exception.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/std/cxx.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/std/dinkumware.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/std/libcomo.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/std/modena.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/std/msl.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/std/roguewave.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/std/sgi.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/std/stdcpp3.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/std/stlport.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/library/std/vacpp.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/aix.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/detail/os_detected.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/amigaos.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/android.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/beos.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/bsd.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/macos.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/ios.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/bsd/bsdi.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/bsd/dragonfly.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/bsd/free.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/bsd/open.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/bsd/net.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/cygwin.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/haiku.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/hpux.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/irix.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/linux.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/os400.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/qnxnto.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/solaris.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/unix.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/vms.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/os/windows.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/other.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/other/endian.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/platform.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/platform/mingw.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/detail/platform_detected.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/platform/windows_desktop.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/platform/windows_store.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/platform/windows_phone.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/platform/windows_runtime.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/hardware.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/hardware/simd.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/hardware/simd/x86.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/hardware/simd/x86/versions.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/hardware/simd/x86_amd.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/hardware/simd/x86_amd/versions.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/hardware/simd/arm.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/hardware/simd/arm/versions.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/hardware/simd/ppc.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/hardware/simd/ppc/versions.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/predef/version.h \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/spinlock_sync.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/spinlock_pt.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/spinlock_gcc_arm.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/spinlock_w32.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_interlocked.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/spinlock_nt.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_pt.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_clang.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_snc_ps3.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_acc_ia64.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_gcc_ia64.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_vacpp_ppc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_cw_ppc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_gcc_ppc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_gcc_mips.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_sync.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_gcc_sparc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_w32.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_base_aix.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_counted_impl.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/quick_allocator.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/lightweight_mutex.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/lwm_nop.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/lwm_pthreads.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/lwm_win32_cs.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/type_with_alignment.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/alignment_of.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_pod.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/conditional.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/core/addressof.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_convertible.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/make_shared.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/make_shared_object.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/move/core.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/move/detail/config_begin.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/move/detail/workaround.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/move/detail/type_traits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/move/detail/meta_utils.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/move/detail/meta_utils_core.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/move/detail/config_end.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/move/utility_core.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_forward.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/make_shared_array.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/array_count_impl.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/array_allocator.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/align/align.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/align/detail/align_cxx11.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/align/detail/align.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/align/detail/is_alignment.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/array_traits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/array_utility.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/has_trivial_constructor.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_default_constructible.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/has_trivial_destructor.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_destructible.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/detail/sp_if_array.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/smart_ptr/allocate_shared_array.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/interface_oarchive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/oserializer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/greater_equal.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/extended_type_info_typeid.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/factory.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/comparison/greater.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/comparison/less.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/comparison/less_equal.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/logical/not.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/smart_cast.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/remove_pointer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/or.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/remove_extent.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/version.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/less.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/comparison.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/not_equal_to.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/mpl/less_equal.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/void_cast.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_virtual_base_of.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_base_of.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/basic_oserializer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/basic_serializer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/basic_pointer_oserializer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/archive_serializer_map.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/check.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/string.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/serialization/item_version_type.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/binary_iarchive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/binary_iarchive_impl.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/basic_binary_iprimitive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/basic_binary_iarchive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/common_iarchive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/basic_iarchive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/basic_pointer_iserializer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/interface_iarchive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/iserializer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/core/no_exceptions_support.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/has_new_operator.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/detail/basic_iserializer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/stream.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/constants.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/ios.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/config/wide_streams.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/char_traits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/config/overload_resolution.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/config/gcc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/forward.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/config/limits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/push_params.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/repetition/enum_binary_params.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/repetition/repeat_from_to.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/iostream.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/select.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/stream_buffer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/streambuf/direct_streambuf.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/error.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/execute.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/iteration/local.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/utility/result_of.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/facilities/intercept.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/utility/declval.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/utility/enable_if.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/core/enable_if.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/functional.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/close.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/categories.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/flush.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/dispatch.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/traits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/bool_trait_def.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/template_params.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/is_iterator_range.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/config/disable_warnings.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/config/enable_warnings.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/select_by_size.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/wrap_unwrap.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/enable_if_stream.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/traits_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/ref.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/core/ref.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/utility/addressof.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/iterator_range.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/iterator_range_core.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iterator/iterator_traits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iterator/iterator_facade.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iterator.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iterator/interoperable.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iterator/detail/config_def.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iterator/detail/config_undef.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iterator/iterator_categories.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iterator/detail/facade_iterator_category.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/detail/indirect_traits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iterator/detail/enable_if.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/add_const.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/add_pointer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/functions.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/begin.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/config.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/detail/begin.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/iterator.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/range_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/mutable_iterator.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/detail/extract_optional_type.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/detail/msvc_has_iterator_workaround.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/const_iterator.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/detail/common.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/detail/sfinae.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/end.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/detail/end.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/detail/implementation_help.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/size.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/size_type.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/difference_type.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/has_range_iterator.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/concepts.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/concept_check.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/concept/assert.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/concept/detail/msvc.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/concept/detail/backward_compatibility.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/concept/detail/has_constraints.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/concept/detail/borland.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/concept/detail/general.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/conversion_traits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/concept/usage.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/concept/detail/concept_def.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/seq/for_each_i.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/seq/enum.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/concept/detail/concept_undef.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iterator/iterator_concepts.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/value_type.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/detail/misc_concept.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/make_unsigned.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_signed.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/is_unsigned.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/add_volatile.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/detail/has_member_size.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/utility.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/utility/base_from_member.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/utility/binary.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/control/deduce_d.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/seq/cat.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/seq/transform.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/arithmetic/mod.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/preprocessor/arithmetic/detail/div_base.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/utility/identity_type.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/function_traits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/next_prior.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/integral_promotion.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/make_signed.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/has_plus.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/detail/has_binary_operator.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/has_plus_assign.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/has_minus.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/has_minus_assign.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/distance.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/empty.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/rbegin.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/reverse_iterator.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iterator/reverse_iterator.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iterator/iterator_adaptor.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/rend.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/algorithm/equal.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/detail/safe_bool.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/range/iterator_range_io.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/streambuf.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/operations_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/adapter/non_blocking_adapter.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/read.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/char_traits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/seek.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/positioning.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/config/codecvt.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/config/fpos.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/write.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/optional.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/aligned_storage.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/streambuf/linked_streambuf.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/operations.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/imbue.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/input_sequence.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/optimal_buffer_size.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/output_sequence.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/adapter/concept_adapter.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/concepts.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/default_arg.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/call_traits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/config/unreachable_return.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/device/null.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/buffer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/checked_operations.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/get.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/put.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/double_object.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/call_traits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/detail/call_traits.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/push.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/adapter/range_adapter.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/pipeline.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/resolve.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/detail/is_incrementable.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/type_traits/detail/bool_trait_undef.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/adapter/mode_adapter.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/adapter/output_iterator_adapter.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/is_dereferenceable.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/device/array.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/broken_overload_resolution/stream_buffer.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/broken_overload_resolution/forward.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/iostreams/detail/broken_overload_resolution/stream.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/xml_oarchive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/basic_text_oprimitive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/io/ios_state.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/io_fwd.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/dinkumware.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/basic_xml_oarchive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/xml_iarchive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/basic_text_iprimitive.hpp \
		/usr/local/Cellar/boost/1.63.0/include/boost/archive/basic_xml_iarchive.hpp \
		container_device.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/main.o main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

